### PR TITLE
Process identityToken generated From refresh_token

### PR DESCRIPTION
**Pull request by noriel0010**
Added Another Struct to process **identityToken** that is generated from **refresh_token**.

### CODE REVIEW

**Comment by noriel0010** [comment]
**identityToken** generated from _refresh_token_ is not having **c_hash** and **auth_time** claims, which throws missing claim exception.

**Comment by hywak** [comment]
@noriel0010 I can't find information if it's possible to generate Apple JWT with `at_hash`. Please test your token with JWT debugger here https://jwt.io/#debugger-io and see what is the payload of your token. Also you can pass your old (expired) token here I can debug it for you.

Not sure where did you take `at_hash` from? Most probably you have to replace `at_hash` with `c_hash` here `src/Auth/Factory/AppleJwtStructFactory.php:51`

**Comment by noriel0010** [comment]
below is the example of Apple JWT generated from refresh_token

jqt

**Comment by noriel0010** [comment]
Hello @hywak here is the sample payload of Apple JWT generated from refresh_token. But I'm Closing this request currently, I think I missed something, sorry for the inconvenience and Thank you so much!
jqt

**Comment by hywak** [comment]
I see. I'm not sure now if I understand correctly your previous question. about missing claims. Is it the problem to you that claims are missing or you just explained the reason why you created a JwtRefreshIdTokenPayload and the method to create it?

Generally, PR is OK but there are tests missing.

**Comment by noriel0010** [comment]
Both, the reason why I created the  JwtRefreshIdTokenPayload is to solve the missing claim issue that we're facing right now using your sdk. I didn't modify your main method, instead I created another method and the JwtRefreshIdTokenPayload for the missing claim. I was hoping you could see my PR and somehow test your sdk using identityToken that is generated from apple refresh_token to see the missing claim issue. I wish I could paste some identityToken (from apple refresh_token) here but I couldn't since it contains some of my account details too.

**Comment by noriel0010** [comment]
I sent you some expired token privately through your email. What I did right now so we could use your sdk, was to implement my changes inside the vendor directory. And use it like this.

```
            try {
                //code...
                $extracted = $appleJwtFetchingService->getJwtPayload($token);
            } catch (\Throwable $th) {
                //throw $th;
                $extracted = $appleJwtFetchingService->getRefreshJwtPayload($token);
            }
```

catching the missing claim issue  and then use my additional method so we can have the data needed.

**Pull request closed without merging**
