### PR TITLE
Switch to Guzzle 6

### PR DESCRIPTION
**Pull request by bastienu**
Hi,

Your package seems to be perfect... but you are using Guzzle 7. However, Guzzle 7 is not necessary for this package to be fully functionnal, Guzzle 6 is enough. Moreover, when you are using Laravel 7, using Guzzle 7 is blocking the installation. 

So, can you use Guzzle 6 in this package to make it run for everyone ? :-)

Thanks a lot !

### CODE REVIEW

**Comment by bastienu** [comment]
Or maybe only add in the composer.json that we can use the version 6.0 ?

Like this : 
```json
"guzzlehttp/guzzle": "^6.0|^7.0",
```

**Review by hywak — CHANGES_REQUESTED** [review]
Please change guzzle version to `^6.0|^7.0` as you suggested in the pull request description.

**Comment by hywak** [comment]
Hey @bastienu,

Thank you for your pull request. I've reviewed your changes and tested locally code on Guzzle 6.5.5 installed accordingly to your suggestion (`"guzzlehttp/guzzle": "^6.0|^7.0",`).

**Comment by bastienu** [comment]
Changes done :-)

**Review by hywak — APPROVED** [review]

**Comment by hywak** [comment]
@bastienu your changes are visible since version `1.1.0`.

**Pull request merged**
